// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./components/base/index.vue')['default']
    Canvas: typeof import('./components/canvas/index.vue')['default']
    Im: typeof import('./components/im/index.vue')['default']
  }
}

export { }
